### ISSUE TITLE
allow for java -jar usage

### ISSUE THREAD

**Issue by seebi** [SmartDataAnalytics/RdfProcessingToolkit#10]
currently java -jar runs are not possible:

```
java -jar /usr/src/app/sparql-integrate-debian-cli/target/sparql-integrate-debian-cli-1.0.0.jar
no main manifest attribute, in /usr/src/app/sparql-integrate-debian-cli/target/sparql-integrate-debian-cli-1.0.0.jar
```

Please extend in order to allow more easy usage patterns ...

**Comment by Aklakan** [comment]
sparql-integrate contains a separate command line tool called [NGS](https://github.com/SmartDataAnalytics/SparqlIntegrate/blob/develop/README-NGS.md)
Either we have to publish 2 jars with pretty much the same dependencies (bad) or we provide separate 'super-commands' that then delegate to the existing machinery.
```
java -jar bundle.jar ngs head -n 10 file.trig
java -jar bundle.jar integrate arg1... arg2
```
This approach looks actually quite ok

**Comment by Aklakan** [comment]
Since version 1.0.6 the jar bundle is self-running
